### ISSUE TITLE
Provide registration interface for all Roles

### ISSUE THREAD

**Issue by amrap030** [taia-x/taia-x#65]
### Tasks

- [x] provide registration for Consumer
- [x] provide registration for Certifier
- [x] provide registration for Provider

**Comment by amrap030** [comment]
I currently created the following frontend components:

<img width="1424" alt="Bildschirmfoto 2021-11-22 um 23 01 25" src="https://user-images.githubusercontent.com/35061229/142942548-aa765fa1-db51-41b1-b42b-78f420cd7913.png">

The idea is, that you have to execute a transaction, after choosing one of the roles. If we implement it similar to the resources, that @alvaro-alonso provided, I think the smart contract has to implement functions like MakeConsumer, MakeCertifier and MakeProvider. These functions are then executed after registration and the user then automatically acts with the respective role for each following transaction.

The interaction with the smart contract is open.

**Comment by eliodemollari** [comment]
@amrap030 Do you have already something implemented for this ticket, I would like to see it

**Comment by amrap030** [comment]
Merged via #75
